"use client";
import { useRef } from "react";
import { useReactToPrint } from "react-to-print";

export default function Print() {
  const componentRef = useRef<HTMLElement | null>(null);
  const handlePrint = useReactToPrint({
    content: () => componentRef.current!,
  });

  return (
    <>
      <div
        className="App bg-orange-200 p-4"
        ref={componentRef as React.RefObject<HTMLDivElement>}
      >
        <div className="header flex justify-between items-center">
          <span className="logo text-3xl font-bold text-orange-800">REAs</span>
          <nav className="flex gap-4 ">
            <span className="text-orange-800">Blog</span>
            <span className="text-orange-800">Categories</span>
            <span className="text-orange-800">Tags</span>
          </nav>
        </div>
        <div className="hero-section mt-4">
          <h1 className="text-4xl font-bold text-orange-800">
            The Joys of Buying Over Building
          </h1>
        </div>
        <main className="mt-4">
          <h2 className="features-title text-2xl font-bold text-orange-800">
            Some features
          </h2>
          <div className="features mt-2 flex gap-2">
            <span className="active bg-orange-500 text-white px-2 py-1 rounded">
              House 1
            </span>
            <span className="bg-orange-500 text-white px-2 py-1 rounded">
              House 2
            </span>
            <span className="bg-orange-500 text-white px-2 py-1 rounded">
              House 3
            </span>
          </div>
          <p className="mt-4 text-orange-800">
            In the grand game of acquiring a new abode, the age-old debate
            between buying an existing house and building a brand-new one
            continues to captivate prospective homeowners. Both options have
            their merits, but let's take a lighthearted stroll through the perks
            of opting for a pre-built dwelling.
          </p>
          <p className="mt-4 text-orange-800">
            Then there's the joy of exploring neighborhoods with character and
            history. Buying a house often means settling into an established
            community, complete with charming local spots and friendly
            neighbors. Sure, you might not have personally picked out every
            detail of your home, but there's a unique charm in discovering the
            stories embedded in its walls and the quirks that come with a house
            that's been lived in.
          </p>
          <p className="mt-4 text-orange-800">
            In the end, whether you're swiping right on a charming existing home
            or swaying to the rhythm of your own construction symphony, the
            decision between buying and building is a personal one. But hey,
            there's something undeniably delightful about stepping into a house
            and immediately feeling at home – no hard hat required.
          </p>
          <p className="mt-4 text-orange-800">Article generated by ChatGPT</p>
        </main>
      </div>
      <button
        className="mt-4 bg-orange-500 text-white px-4 py-2 rounded"
        onClick={handlePrint}
      >
        Print article
      </button>
    </>
  );
}
