import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/providers/toaster-provider";

import dynamic from "next/dynamic";
const NextProgress = dynamic(
  () => import("@/components/providers/next-progress"),
  {
    ssr: false,
  }
);

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextProgress />
        {/* <ConfettiProvider /> */}
        <ToastProvider />
        {children}
      </body>
    </html>
  );
}
